#!/usr/bin/env python3
"""
build_guestbook.py -- turn signed issues into guestbook.json.

The book is signed on guestbook.html, which opens a pre-filled issue on the
repository. This reads those issues back and writes the file the page renders,
so nobody has to transcribe anything by hand.

    gh issue list --state open --limit 200 --json number,title,body,author,createdAt \
      | python tools/build_guestbook.py

Reads the issue list as JSON on stdin, merges it with guestbook.seed.json
(hand-written entries that always appear), and writes guestbook.json.

MODERATION, such as it is:
  * only issues whose title starts "guestbook:" are considered
  * closing an issue removes the entry -- the file is rebuilt from scratch
    every run, so closing or deleting is the delete button
  * everything is length-capped and stripped to plain text
  * bots are ignored

guestbook.json is GENERATED. Do not hand-edit it; edit guestbook.seed.json.
"""

from __future__ import annotations

import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "guestbook.json")
SEED = os.path.join(ROOT, "guestbook.seed.json")

MAX_HANDLE = 32
MAX_WHERE = 40
MAX_TEXT = 600
MAX_ENTRIES = 300

TITLE = re.compile(r"^\s*guestbook\s*:", re.I)
FOOTER = re.compile(r"\n-{3,}\s*\nsent from the book.*$", re.I | re.S)


def clean(s: str, cap: int) -> str:
    """Plain text only, collapsed whitespace, capped."""
    s = str(s or "")
    s = s.replace("\r\n", "\n").replace("\r", "\n")
    # no markup, no control characters
    s = re.sub(r"<[^>]*>", "", s)
    s = "".join(ch for ch in s if ch == "\n" or ch >= " ")
    # at most one blank line in a row
    s = re.sub(r"\n{3,}", "\n\n", s)
    s = re.sub(r"[ \t]{2,}", " ", s)
    return s.strip()[:cap]


def one_line(s: str, cap: int) -> str:
    return clean(s, cap).replace("\n", " ").strip()


def parse(issue: dict) -> dict | None:
    """Pull an entry out of one issue, in the format the page writes."""
    title = issue.get("title") or ""
    if not TITLE.match(title):
        return None

    author = (issue.get("author") or {})
    login = author.get("login") or "anonymous"
    if author.get("is_bot") or login.endswith("[bot]"):
        return None

    body = (issue.get("body") or "").replace("\r\n", "\n")
    body = FOOTER.sub("", body)

    handle = where = date = ""
    text = body

    m = re.match(
        r"\s*handle:(?P<h>[^\n]*)\n+where:(?P<w>[^\n]*)\n+date:(?P<d>[^\n]*)\n(?P<t>.*)",
        body, re.S | re.I,
    )
    if m:
        handle = m.group("h")
        where = m.group("w")
        date = m.group("d")
        text = m.group("t")
    else:
        # signed by hand, straight on the tracker: still let it in
        handle = login
        date = (issue.get("createdAt") or "")[:10]
        if date:
            y, mo, d = date.split("-")
            date = "%s.%s.%s" % (d, mo, y[2:])

    handle = one_line(handle, MAX_HANDLE) or login
    where = one_line(where, MAX_WHERE)
    if where in ("-", "—"):
        where = ""
    date = one_line(date, 12)
    text = clean(text, MAX_TEXT)

    if not text:
        return None

    return {
        "handle": handle,
        "where": where,
        "at": date,
        "text": text,
        "issue": issue.get("number"),
        "by": login,
    }


def load_seed() -> list:
    if not os.path.exists(SEED):
        return []
    try:
        d = json.load(io.open(SEED, encoding="utf-8"))
        return d.get("entries", []) if isinstance(d, dict) else list(d)
    except Exception as e:                                   # noqa: BLE001
        print("seed file unreadable, ignoring it: %s" % e, file=sys.stderr)
        return []


def main() -> int:
    raw = sys.stdin.read().strip()
    issues = []
    if raw:
        try:
            issues = json.loads(raw)
        except json.JSONDecodeError as e:
            print("could not read the issue list: %s" % e, file=sys.stderr)
            return 1
    if not isinstance(issues, list):
        issues = []

    signed = []
    for it in issues:
        e = parse(it)
        if e:
            signed.append(e)

    # newest issue first, then the hand-written seeds underneath
    signed.sort(key=lambda e: -(e.get("issue") or 0))
    entries = (signed + load_seed())[:MAX_ENTRIES]

    doc = {
        "_README": (
            "GENERATED by tools/build_guestbook.py from the repository's issues. "
            "Do not hand-edit this file - edit guestbook.seed.json for permanent "
            "entries, and close an issue to remove the one it produced."
        ),
        "count": len(entries),
        "entries": entries,
    }

    new = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"
    old = io.open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""

    if new == old:
        print("guestbook.json unchanged (%d entries)" % len(entries))
        return 0

    io.open(OUT, "w", encoding="utf-8", newline="\n").write(new)
    print("guestbook.json written: %d entries (%d signed, %d seed)"
          % (len(entries), len(signed), len(entries) - len(signed)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
